### ISSUE TITLE
Problem for enabling the plugin in godot

### ISSUE THREAD

**Issue by Parabolakit** [ScheiklP/sofa_godot#2]
Hi scheikIP, 

Nice to meet you. I want to use your plugin to create SOFA scene.
I create a new project in godot and create one addons folder in the directory of project. Then I add clone sofa_godot plugin to addons folder.
There is a problem when I enable the plugin,
Unable to load addon script from path: 'res://addons/sofa_godot/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/sofa_godot/plugin.cfg' to prevent further errors.

Thanks for your help:D

Best,
Parabola

**Comment by ScheiklP** [comment]
Hi @Parabolakit ,
since the interest in sofa_godot was relatively small in the community so far, I have not updated the project to newer Godot versions.
Which Godot version did you try?

Cheers,
Paul

**Comment by Parabolakit** [comment]
> Hi @Parabolakit ,
> 
> since the interest in sofa_godot was relatively small in the community so far, I have not updated the project to newer Godot versions.
> 
> Which Godot version did you try?
> 
> 
> 
> Cheers,
> 
> Paul

hi Paul,

Thanks for your prompt reply. 
I used the version  3.5.1 that u have tested successfully. 

Best,
Parabola

**Comment by ScheiklP** [comment]
Hi @Parabolakit ,
did you also use the sofa_env commit that was valid on release?
https://github.com/ScheiklP/sofa_env/tree/d0d197d4bda74338e8b6aa1e5a72a9c715f7f73e

Cheers,
Paul

**Comment by Parabolakit** [comment]
> Hi @Parabolakit , did you also use the sofa_env commit that was valid on release? https://github.com/ScheiklP/sofa_env/tree/d0d197d4bda74338e8b6aa1e5a72a9c715f7f73e
> 
> Cheers, Paul

Dear Paul,

I can run the code to train the environments you provided. Are they related that should be stored in the same directory?

Best,
Parabola

**Comment by ScheiklP** [comment]
Hi @Parabolakit ,
yes, sofa_godot uses the sofa_templates from sofa_env, so their versions also have to match.

Cheers,
Paul

**Comment by Parabolakit** [comment]
> Hi @Parabolakit , yes, sofa_godot uses the sofa_templates from sofa_env, so their versions also have to match.
> 
> Cheers, Paul

Hi Paul,

My SOFA version is 23.06. Which version should I use?

Best,
Parabola

**Comment by ScheiklP** [comment]
Hi @Parabolakit,
SOFA version 23.06. should be fine, but make sure you are also using the correct commit of sofa_env https://github.com/ScheiklP/sofa_env/tree/d0d197d4bda74338e8b6aa1e5a72a9c715f7f73e

- SOFA is the FEM simulation / physics backend
- sofa_env is all the nice python code to use SOFA as a physics backend for reinforcement learning envs

Cheers,
Paul

**Comment by Parabolakit** [comment]
Hi Paul,

Should I activate conda environment before adding the plugin to godot? As I use the godot UI to do this, I am still no ideas for the problems.
![image](https://github.com/ScheiklP/sofa_godot/assets/143982693/3526b241-76fd-4a05-8745-a49f344aa329)

Best,
Parabola

**Comment by ScheiklP** [comment]
Yes, please activate the conda environment.

**Comment by Parabolakit** [comment]
> Yes, please activate the conda environment.

It works, thanks!!!!
