### ISSUE TITLE
cannot enable plugin , do not have a conda environment

### ISSUE THREAD

**Issue by saketh2002** [ScheiklP/sofa_godot#3]
Hi
Is conda environment necessary for enabling the godot plugin ? I am unable to enable the plugin in godot. I installed SOFA on system and I pass sofapython3 root and python3 path every time to run a scene description script in runSofa. I tried to install it in a conda environment, but my system keeps crashing and I didnt pursue the option further as sofa was comfortably running in system without conda. Kindly let me know if there is a fix for this

**Comment by ScheiklP** [comment]
Hi @saketh2002 ,
you technically do not need conda, but I highly recommend it, because you need `sofa_env` for `sofa_godot` to work.

What type of system are you on? Ubuntu 22.04?

Cheers,
Paul

**Comment by saketh2002** [comment]
I am currently running sofa_env scipts in Ubuntu 20.08 system. I use ./runSofa for running the scene description files. I can also run the RL training files on my system without any issues. I want to create a custom environment using godot, as I found it comparatively easier compared to writing the code from scratch. But somehow the plugin is not being loaded in godot. Is the python version a problem ? I am currently running my system in python 3.8

**Comment by ScheiklP** [comment]
Hi @saketh2002 ,
that sounds like similar problem to https://github.com/ScheiklP/sofa_godot/issues/2 
Could you read through that issue and let me know, whether that also works for you?

Cheers,
Paul

**Comment by saketh2002** [comment]
Hi @ScheiklP ,
I did try the solution in #2 But as I mentioned before, my conda keeps crashing when activated, hence I had to resort to using system for running sofa_env and sofa_zoo files (which are working properly, when I export environment variables to the terminal - sofa root, python path, sofa python3 root). It would be great if you could provide me with an alternative to conda

**Comment by ScheiklP** [comment]
Hi @saketh2002 ,
did you also make sure that the commits between sofa_godot and sofa_env match?
That was ultimately the problem in https://github.com/ScheiklP/sofa_godot/issues/2

Cheers,
Paul

**Comment by saketh2002** [comment]
I did verify that, on inspecting in godot, It was showing an error like this. - error 8115, cant load resource.
![Screenshot from 2024-04-16 15-30-28](https://github.com/ScheiklP/sofa_godot/assets/65168029/cc6c41c6-cbac-462e-ad13-f9778fb2a309)
 Could this might be causing the problem ?

**Comment by ScheiklP** [comment]
I am actually not sure.
Maybe @chhas could help us with that?

**Comment by chhas** [comment]
@ScheiklP, looks like upon release we changed the naming and must have forgotten to adapt the file paths. 

@saketh2002, renaming the plugin folder from `sofa_godot` to `sofa_godot_plugin` (see screenshot below) should suffice for the plugin to be loaded.
However, to use this plugin without a conda environment adaptation of [sofa_python/sofa_python_root.gd](../blob/main/sofa_python/sofa_python_root.gd) is required.

![image](https://github.com/ScheiklP/sofa_godot/assets/10243106/eccf5116-8e75-4935-b5c5-96e334b9517e)

**Comment by saketh2002** [comment]
@chhas  @ScheiklP  Really thanks for the help. It worked. But I just wanted to confirm, does godot only support .obj files ? Because I could see some environments having .stl and .vtk files in sofa env repo. It would be great help to me if it supports .stl files too

**Comment by chhas** [comment]
@saketh2002, glad to hear that sofa_godot is working for you now.
You're right, Godot does not support importing `*.stl` files.
You can use an external tool like [MeshLab](https://www.meshlab.net/) for file conversion.
I also found an [STL Importer](https://godotengine.org/asset-library/asset/961) in the asset library, but I never tested it and don't know if it will work with sofa_godot.

**Comment by saketh2002** [comment]
@chhas  Yeah I am using meshlab. I did try stl plugins but it's just too much effort. Hence I am continuing the work in obj files. Thanks for all the help!

**Comment by ScheiklP** [comment]
Thanks @chhas :)
